# ----------------------------
# Makefile Options
# ----------------------------

NAME = LCD
ICON = icon.png
DESCRIPTION = "CE C Toolchain USBTest"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)